#: include dist.kv
#: include productos.kv
#: include mipedido.kv
ScreenManager:
    MenuScreen:
<MenuScreen>
    name:'menu'
    MDRectangleFlatButton:
        text: 'ingresar'
        pos_hint:{'center_x':0.5,"center_y":0.5}
        on_press: root.manager.current= 'Screen2'
<ProfileScreen>
    name: 'profile'
    MDLabel:
        text: 'Welcome'
        halign: 'center'

<DistribuidoresScreen>
    name: 'distribuidor'
    


